name: Continuous Integration
on: [ pull_request ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install pyshacl
      - run: pyshacl --shacl "Formalisation(shacl)/Core/PiecesShape/Catalog.ttl" --metashacl "Formalisation(shacl)/Core/Example-Data/example-catalog.ttl"
