name: Continuous Integration
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install Hatch
        run: pipx install hatch
        
      - name: Run tests
        run: hatch run pytest
