name: 'Check correct PR branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to master from the develop branch."
          exit 1
